### PR TITLE
Limit integrating CocoaPods to native targets

### LINKED ISSUE #60: Error: Cannot run project that depends on .framework file
Hi there,
I try `XCRemoteCache` `cocoapods plugin` in simple project and it works well.
But after i add a `Firebase/Analytics` and doing pod install i always got this error

Screen Shot 2022-01-26 at 16 16 35
 
I think it's because the `Firebase/Analytic` dependency is a `.framework` instead of `source file`

May i know how to solve this issue?

### PR DESCRIPTION
**Pull request by polac24**
CocoaPods plugin was incorrectly trying to integrate into aggregation targets, which don't have compilation steps to cache. 

The automation integrator is limiting XCRemoteCache integration to native targets only: 
https://github.com/spotify/XCRemoteCache/blob/cdddc5bf194045c6860ace14f9c8cf7d4da5185e/Sources/XCRemoteCache/Commands/Prepare/Integrate/XcodeProjIntegrate.swift#L185

Fixes #60

### CODE REVIEW

File: cocoapods-plugin/lib/cocoapods-xcremotecache/command/hooks.rb [hunk 1]
```diff
@@ -390,6 +392,7 @@ def self.save_lldbinit_rewrite(user_proj_directory)
             installer_context.pods_project.root_object.project_references.each do |subproj_ref|
                 generated_project = Xcodeproj::Project.open("#{pods_proj_directory}/#{subproj_ref[:project_ref].path}")
                 generated_project.native_targets.each do |target|
+                    next unless target.instance_of?(Xcodeproj::Project::Object::PBXNativeTarget)
```
Comment (vasvf) [inline cocoapods-plugin/lib/cocoapods-xcremotecache/command/hooks.rb:395]: line #394 already iterates through native targets

File: cocoapods-plugin/lib/cocoapods-xcremotecache/command/hooks.rb [hunk 2]
```diff
@@ -376,6 +376,8 @@ def self.save_lldbinit_rewrite(user_proj_directory)
           unless installer_context.pods_project.nil?
             # Attach XCRemoteCache to Pods targets
             installer_context.pods_project.targets.each do |target|
+                # Enable only for native targets which can have compilation steps
+                next unless target.instance_of?(Xcodeproj::Project::Object::PBXNativeTarget)
```
Comment (vasvf) [inline cocoapods-plugin/lib/cocoapods-xcremotecache/command/hooks.rb:380]: my bad.

File: cocoapods-plugin/lib/cocoapods-xcremotecache/command/hooks.rb (hunk 1 above)
Comment (polac24) [reply cocoapods-plugin/lib/cocoapods-xcremotecache/command/hooks.rb]: Good catch

File: cocoapods-plugin/lib/cocoapods-xcremotecache/command/hooks.rb (hunk 2 above)
Comment (polac24) [reply cocoapods-plugin/lib/cocoapods-xcremotecache/command/hooks.rb]: changed to `native_targets`

**Review by vasvf — APPROVED** [review]
Not sure if I can approve, but I'll try :)

**Review by aleksandergrzyb — APPROVED** [review]
