### PR TITLE
[CocoaPodsPlugin] Support first-party caching for incremental install

### LINKED ISSUE #18: Pod install fails when using generate_multiple_pod_projects and incremental_installation
CocoaPods introduced `incremental_installation` in 2019 in order to speed up `pod install` times. However, using it in a project causes the `XCRemoteCache` CocoaPods plugin to fail with the following error:

```
[XCRC] XCRemoteCache disabled with error: undefined method `targets' for nil:NilClass
/Users/sethfri/.rvm/gems/ruby-2.6.8/gems/cocoapods-xcremotecache-0.0.2/lib/cocoapods-xcremotecache/command/hooks.rb:342:in `block in <class:XCRemoteCache>': undefined method `targets' for nil:NilClass (NoMethodError)
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/bundler/gems/ios-cocoapods-5e1e0f4700e9/lib/cocoapods/hooks_manager.rb:124:in `block (3 levels) in run'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/bundler/gems/ios-cocoapods-5e1e0f4700e9/lib/cocoapods/user_interface.rb:149:in `message'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/bundler/gems/ios-cocoapods-5e1e0f4700e9/lib/cocoapods/hooks_manager.rb:116:in `block (2 levels) in run'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/bundler/gems/ios-cocoapods-5e1e0f4700e9/lib/cocoapods/hooks_manager.rb:115:in `each'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/bundler/gems/ios-cocoapods-5e1e0f4700e9/lib/cocoapods/hooks_manager.rb:115:in `block in run'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/bundler/gems/ios-cocoapods-5e1e0f4700e9/lib/cocoapods/user_interface.rb:149:in `message'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/bundler/gems/ios-cocoapods-5e1e0f4700e9/lib/cocoapods/hooks_manager.rb:114:in `run'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/bundler/gems/ios-cocoapods-5e1e0f4700e9/lib/cocoapods/installer.rb:649:in `run_plugins_post_install_hooks'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/bundler/gems/ios-cocoapods-5e1e0f4700e9/lib/cocoapods/installer.rb:614:in `perform_post_install_actions'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/gems/chronometer-0.2.0/lib/chronometer.rb:107:in `call'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/gems/chronometer-0.2.0/lib/chronometer.rb:107:in `block in install_method_hook'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/gems/refinement-0.4.1/lib/cocoapods_plugin.rb:8:in `perform_post_install_actions'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/bundler/gems/ios-cocoapods-5e1e0f4700e9/lib/cocoapods/installer.rb:170:in `install!'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/gems/chronometer-0.2.0/lib/chronometer.rb:107:in `call'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/gems/chronometer-0.2.0/lib/chronometer.rb:107:in `block in install_method_hook'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/bundler/gems/ios-cocoapods-5e1e0f4700e9/lib/cocoapods/command/install.rb:52:in `run'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/bundler/gems/ios-cocoapods-5e1e0f4700e9/lib/cocoapods/command.rb:52:in `run'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/bundler/gems/ios-cocoapods-5e1e0f4700e9/bin/pod:55:in `<top (required)>'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/bin/pod:23:in `load'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/bin/pod:23:in `<top (required)>'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/gems/bundler-2.2.30/lib/bundler/cli/exec.rb:58:in `load'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/gems/bundler-2.2.30/lib/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/gems/bundler-2.2.30/lib/bundler/cli/exec.rb:23:in `run'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/gems/bundler-2.2.30/lib/bundler/cli.rb:478:in `exec'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/gems/bundler-2.2.30/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/gems/bundler-2.2.30/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/gems/bundler-2.2.30/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/gems/bundler-2.2.30/lib/bundler/cli.rb:31:in `dispatch'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/gems/bundler-2.2.30/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/gems/bundler-2.2.30/lib/bundler/cli.rb:25:in `start'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/gems/bundler-2.2.30/exe/bundle:49:in `block in <top (required)>'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/gems/bundler-2.2.30/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/gems/bundler-2.2.30/exe/bundle:37:in `<top (required)>'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/bin/bundle:23:in `load'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/bin/bundle:23:in `<main>'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/bin/ruby_executable_hooks:22:in `eval'
	from /Users/sethfri/.rvm/gems/ruby-2.6.8/bin/ruby_executable_hooks:22:in `<main>'
```

There's more detail about the error and potential fixes in https://github.com/CocoaPods/CocoaPods/issues/8604

More details on incremental installation: https://blog.cocoapods.org/CocoaPods-1.7.0-beta/

### PR DESCRIPTION
**Pull request by polac24**
When `Podfile` has enabled incremental_installation, e.g. 
```
install! 'cocoapods',
         :generate_multiple_pod_projects => true
         :incremental_installation => true
```
CocoaPods plugin was failing as `pods_project` is `nil` (see [here](https://github.com/CocoaPods/CocoaPods/issues/8604#issuecomment-472075100)). To fix that, this PR optimistically integrates XCRemoteCache to all targets in the `Pods` project (adding pre/postbuild scripts,`CC`, `SWIFT_EXEC` etc) on a first `Pods` project generation as the plugin will not have a chance to integrate/deintegrate it in consecutive invocations (cocoapods intentionally leaves `Pods` project intact to not generate it without need). 
There will be just a tiny performance penalty if no artifacts are ready and XCRemoteCache is disabled - xcprebuild will quit early when a global `.rc/arc.rc` doesn't exist and fallback to the local compilation.

By the way, I revealed that `generate_multiple_pod_projects` mode is not fully supported (for now). Such setup changes a way the `Pods` project is configured and each pod has a separate .xcodeproj.
To support it, manually modifying each .xcodeproj to integrate XCRemoteCache (build steps build settings etc.), would be required, but so far CocoaPods Plugins interface does not provide a nice API for that ([link](https://rubydoc.info/gems/cocoapods/Pod/Installer/PostInstallHooksContext)).

#### Standard
Screenshot 2021-11-21 at 19 18 52

#### generate_multiple_pod_projects
Screenshot 2021-11-21 at 19 17 39

Fixes #18

### CODE REVIEW

File: cocoapods-plugin/lib/cocoapods-xcremotecache/command/hooks.rb [hunk 1]
```diff
@@ -324,6 +324,28 @@ def self.save_lldbinit_rewrite(user_proj_directory)
           File.delete(xccc_location) if File.exist?(xccc_location)
 
           # Prepare XCRC
+
+          # Pods projects can be generated only once (if incremental_installation is abled)
+          # Always integrate XCRemoteCache to all Pods, in case it will be needed later
+          unless installer_context.pods_project.nil?
+            # Attach XCRemoteCache to Pods targets
```
Comment (polac24) [inline cocoapods-plugin/lib/cocoapods-xcremotecache/command/hooks.rb:331]: This code is just moved from the "RC enabled" flow.

File: cocoapods-plugin/lib/cocoapods-xcremotecache/command/hooks.rb [hunk 2]
```diff
@@ -324,6 +324,28 @@ def self.save_lldbinit_rewrite(user_proj_directory)
           File.delete(xccc_location) if File.exist?(xccc_location)
 
           # Prepare XCRC
+
+          # Pods projects can be generated only once (if incremental_installation is abled)
```
Comment (PatrikBillgren) [inline cocoapods-plugin/lib/cocoapods-xcremotecache/command/hooks.rb:328]:
```suggestion
          # Pods projects can be generated only once (if incremental_installation is enabled)
```

**Review by PatrikBillgren — APPROVED** [review]

**Review by PatrikBillgren — APPROVED** [review]
