### PR TITLE
Switch to local PCH headers compilation

### LINKED ISSUE #37: "error: missing input file" during building as a consumer
Xcode config: Automatic integration

Backend: backend-example docker image

Error log:

```
error: missing input file
/Users/xxx/Library/Developer/Xcode/DerivedData/MyProject-grtwydkopfrbzbfwavurkuenidfb/Build/Intermediates.noindex/PrecompiledHeaders/SharedPrecompiledHeaders/7220286051759018287/MyProject-prefix.pch.dia:1:1: warning: Could not read serialized diagnostics file: error("Failed to open diagnostics file") (in target 'Target' from project 'MyProject')
Command ProcessPCH++ failed with a nonzero exit code
```

This happened during build as consumer. I had upload all the files to my server with producer mode.
I crawled the network during build, and all the `GET` request from the server is succeed.

### PR DESCRIPTION
**Pull request by polac24**
To support PCH (precompilation of C headers) in ObjC headers, this PR always triggers the headers compilation locally. That step should be relatively quick so it will not contribute significantly to the total build time and caching it within Xcode process is not trivial.
Xcode, contrary to the compilation processes, compiles `.pch` files to the project-wide location (by default `PrecompiledHeaders/SharedPrecompiledHeaders`) with a hashed directory name. It means that from a clang wrapper process (xccc) finding a location where a marker file (discriminator if we should stub the compilation step of compile locally) should adopt a different technique than the ".m" files do - looking for ../../.. of the "-MF" argument is not valid anymore.

As `.d` file of the compilation step (a file that lists all compilation dependencies) does not refer to the location of the compiled header but just the .pch file within a project, to not overengineer the PCH support, I suggest going with the simples solution and just fallback to the local compilation. In case that will not be enough, we can come up with a more optimized solution later.

_Example of the Xcode PCH generation log:_
<details>
ProcessPCH #{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Intermediates.noindex/PrecompiledHeaders/SharedPrecompiledHeaders/14267228059646731042/PrefixHeader.pch.gch #{Home}/#{Project}/DebugPrefix/PrefixHeader.pch normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler (in target 'TargetObjCRoot' from project 'DebugPrefix')
    cd #{Home}/#{Project}/DebugPrefix
    
    Precompile of '#{Home}/#{Project}/DebugPrefix/PrefixHeader.pch' required by '#{Home}/#{Project}/DebugPrefix/TargetObjCRoot/TargetObjCRoot.m'
    
    /Applications/Xcode-1321.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c-header -target arm64-apple-ios15.2-simulator -fmessage-length\=0 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit\=0 -std\=gnu11 -fobjc-arc -fobjc-weak -fmodules -fmodules-cache-path\=#{Home}/Library/Developer/Xcode/DerivedData/ModuleCache.noindex -fmodules-prune-interval\=86400 -fmodules-prune-after\=345600 -fbuild-session-file\=#{Home}/Library/Developer/Xcode/DerivedData/ModuleCache.noindex/Session.modulevalidation -fmodules-validate-once-per-build-session -Wnon-modular-include-in-framework-module -Werror\=non-modular-include-in-framework-module -fmodule-name\=TargetObjCRoot -Wno-trigraphs -fpascal-strings -O0 -fno-common -Wno-missing-field-initializers -Wno-missing-prototypes -Werror\=return-type -Wdocumentation -Wunreachable-code -Wquoted-include-in-framework-header -Wno-implicit-atomic-properties -Werror\=deprecated-objc-isa-usage -Wno-objc-interface-ivars -Werror\=objc-root-class -Wno-arc-repeated-use-of-weak -Wimplicit-retain-self -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wunused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconditional-uninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wno-float-conversion -Wnon-literal-null-conversion -Wobjc-literal-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wundeclared-selector -Wdeprecated-implementations -DDEBUG\=1 -DOBJC_OLD_DISPATCH_PROTOTYPES\=0 -isysroot /Applications/Xcode-1321.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator15.2.sdk -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -g -Wno-sign-conversion -Winfinite-recursion -Wcomma -Wblock-capture-autoreleasing -Wstrict-prototypes -Wno-semicolon-before-method-body -Wunguarded-availability -fobjc-abi-version\=2 -fobjc-legacy-dispatch -index-store-path #{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Index/DataStore -iquote #{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Intermediates.noindex/DebugPrefix.build/Debug-iphonesimulator/TargetObjCRoot.build/TargetObjCRoot-generated-files.hmap -I#{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Intermediates.noindex/DebugPrefix.build/Debug-iphonesimulator/TargetObjCRoot.build/TargetObjCRoot-own-target-headers.hmap -I#{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Intermediates.noindex/DebugPrefix.build/Debug-iphonesimulator/TargetObjCRoot.build/TargetObjCRoot-all-non-framework-target-headers.hmap -ivfsoverlay #{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Intermediates.noindex/DebugPrefix.build/Debug-iphonesimulator/TargetObjCRoot.build/all-product-headers.yaml -iquote #{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Intermediates.noindex/DebugPrefix.build/Debug-iphonesimulator/TargetObjCRoot.build/TargetObjCRoot-project-headers.hmap -I#{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Products/Debug-iphonesimulator/include -I#{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Intermediates.noindex/DebugPrefix.build/Debug-iphonesimulator/TargetObjCRoot.build/DerivedSources-normal/arm64 -I#{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Intermediates.noindex/DebugPrefix.build/Debug-iphonesimulator/TargetObjCRoot.build/DerivedSources/arm64 -I#{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Intermediates.noindex/DebugPrefix.build/Debug-iphonesimulator/TargetObjCRoot.build/DerivedSources -F#{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Products/Debug-iphonesimulator -fdebug-prefix-map\=#{Home}/#{Project}/DebugPrefix\=/xxx -c #{Home}/#{Project}/DebugPrefix/PrefixHeader.pch -MD -MT dependencies -MF #{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Intermediates.noindex/PrecompiledHeaders/SharedPrecompiledHeaders/14267228059646731042/PrefixHeader.pch.d -iquote #{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Intermediates.noindex/DebugPrefix.build/Debug-iphonesimulator/TargetObjCRoot.build/TargetObjCRoot-generated-files.hmap -I#{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Intermediates.noindex/DebugPrefix.build/Debug-iphonesimulator/TargetObjCRoot.build/TargetObjCRoot-own-target-headers.hmap -I#{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Intermediates.noindex/DebugPrefix.build/Debug-iphonesimulator/TargetObjCRoot.build/TargetObjCRoot-all-non-framework-target-headers.hmap -ivfsoverlay #{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Intermediates.noindex/DebugPrefix.build/Debug-iphonesimulator/TargetObjCRoot.build/all-product-headers.yaml -iquote #{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Intermediates.noindex/DebugPrefix.build/Debug-iphonesimulator/TargetObjCRoot.build/TargetObjCRoot-project-headers.hmap -I#{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Products/Debug-iphonesimulator/include -I#{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Intermediates.noindex/DebugPrefix.build/Debug-iphonesimulator/TargetObjCRoot.build/DerivedSources-normal/arm64 -I#{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Intermediates.noindex/DebugPrefix.build/Debug-iphonesimulator/TargetObjCRoot.build/DerivedSources/arm64 -I#{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Intermediates.noindex/DebugPrefix.build/Debug-iphonesimulator/TargetObjCRoot.build/DerivedSources -o #{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Intermediates.noindex/PrecompiledHeaders/SharedPrecompiledHeaders/14267228059646731042/PrefixHeader.pch.gch --serialize-diagnostics #{Home}/Library/Developer/Xcode/DerivedData/DebugPrefix-fqvdsqxngtnuczfkdfgdcbjxvkpy/Build/Intermediates.noindex/PrecompiledHeaders/SharedPrecompiledHeaders/14267228059646731042/PrefixHeader.pch.dia

</details>

Fixes #37

### CODE REVIEW

File: Sources/XCRemoteCache/Commands/Prepare/CCWrapperBuilder.swift [hunk 1]
```diff
@@ -438,6 +447,14 @@ class TemplateBasedCCWrapperBuilder: CCWrapperBuilder {
                 }
             }
 
+           // null-terminating the args array needed for local compilation fallback
+           clang_args[argc] = NULL;
+
+           // Verify mode. If caching this mode is not supported, fallback to local compilation
```
Comment (polac24) [inline Sources/XCRemoteCache/Commands/Prepare/CCWrapperBuilder.swift:453]:
```suggestion
           // Verify mode. Even a target is cached, this mode is not supported. Fallback to the local compilation
```

**Review by SeanWit — APPROVED** [review]
LGTM

File: Tests/XCRemoteCacheTests/Commands/XCCCTests.swift [hunk 2]
```diff
@@ -332,11 +333,31 @@ class TemplateBasedCCWrapperBuilderTests: FileXCTestCase {
         XCTAssertNotEqual(newFileOutputData, Data())
     }
 
+    func testPCHCompilationFallbacks() throws {
+        // Marker is empty to mimic the new file scenario
+        let pchFile = directory.appendingPathComponent("input.pch")
+        createValidPCCFile(pchFile)
```
Comment (aleksandergrzyb) [inline Tests/XCRemoteCacheTests/Commands/XCCCTests.swift:339]:
```suggestion
        createValidPCHFile(pchFile)
```

File: Tests/XCRemoteCacheTests/Commands/XCCCTests.swift [hunk 3]
```diff
@@ -332,11 +333,31 @@ class TemplateBasedCCWrapperBuilderTests: FileXCTestCase {
...
+        XCTAssertTrue(fileManager.fileExists(atPath: outputFile.path))
+    }
+
     /// Creates a simple C code in the location
     private func createValidCFile(_ location: URL) {
         fileManager.createFile(atPath: location.path, contents: "int main(){}".data(using: .utf8), attributes: nil)
     }
 
+    /// Creates a simple PCH code in the location
+    private func createValidPCCFile(_ location: URL) {
```
Comment (aleksandergrzyb) [inline Tests/XCRemoteCacheTests/Commands/XCCCTests.swift:353]:
```suggestion
    private func createValidPCHFile(_ location: URL) {
```

**Review by aleksandergrzyb — APPROVED** [review]

**Review by aleksandergrzyb — APPROVED** [review]
